import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/app/components/head'; // 注意：确保文件名大小写匹配，有时是 Header.tsx
// 1. 引入这一行！
import { ThemeProvider } from '@/app/context/ThemeContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zoolin Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 2. 关键修改：用 ThemeProvider 把 Header 和 children 都包起来 */}
        <ThemeProvider>
            
            {/* Header 在这里面，它才能用 useTheme 切换颜色 */}
            <Header /> 
            
            {children}
            
        </ThemeProvider>
      </body>
    </html>
  );
}